

# SRC +=  examples/MCU_AssemblyAndCMixing/Src/main.c 

SRC +=  examples/MCU_AssemblyAndCMixing/main.c
ASM += examples/MCU_AssemblyAndCMixing/function.s
ASM += common/startup_stm32f407xx.s

# link script
LDSCRIPT = STM32F407VGTx_FLASH.ld